server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kuang_yun?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username:
    password:
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间
      idle-timeout: 100000
      # 最大连接数
      maximum-pool-size: 10
      # 自动提交
      auto-commit: true
      # 连接最大存活时间(30m)
      max-lifetime: 1800000
      # 连接超时时间(30s)
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.kai.kuangyun.pojo
  configuration:
    map-underscore-to-camel-case: true

jwt:
  # jwt 存储的请求头
  tokenHeader: Authorization
  # jwt 加密解密使用的密钥
  secret: maokai
  # jwt 的超期限时间(60*5*10)
  expiration: 3000
  # jwt 负载中拿到开头
  tokenHead: Cumter

kai:
  resource: /KY_resource